baseURL = "https://nervousturtle.netlify.app/"
title = "Herbivo(R)es"
languageCode = "en-us"
theme = "hugo-theme-m10c"
paginate = 5

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
#  [[menu.main]]
#    identifier = "projects"
#    name = "Projects"
#    url = "/projects/"
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/post/"

[params]
  author = "Herbivores"
  description = "Pain + Reflection = Progress"
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/herbivores"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"
    
    
#  [params.style]
#    darkestColor = "#d35050"
 #   darkColor = "#212121"
  #  primaryColor = "#ffffff"
   # lightColor = "#a2a2a2"
    #lightestColor = "#d3d3d3"
